### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by john-wicc** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#1]
No tooltip appears

**Comment by rowin1** [comment]
Hey @ks-net-positive, thanks for opening an issue and reporting that the extension doesn't work anymore!

If you'd like to work on the fix yourself, you're more than welcome to open up a pull request with the fix. If not, I will take a look this week and have a fix ready

**Comment by rowin1** [comment]
Thanks again for the report.  This issue has been fixed with #2.
