### ISSUE TITLE
Make Pokemon names a clickable link to their record on Smogon

### ISSUE THREAD

**Issue by karllhughes** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#12]
This helps quickly check common movesets and strategies. Here's a demo of it working on [my other branch](https://github.com/karllhughes/Pokemon-Showdown-Enhanced-Tooltips/tree/smogon-links):

![cxa94jducp](https://user-images.githubusercontent.com/1103622/66444208-f48c0b00-ea07-11e9-871f-1616d93177ec.gif)

Would be interested to hear what you think. Thanks!

**Comment by rowin1** [comment]
I love this and I think it makes something that is usually done anyway just that much simpler and quicker.
