### ISSUE TITLE
How do we do releases?

### ISSUE THREAD

**Issue by karllhughes** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#14]
I haven't built a Chrome Extension before, but I assume there's some way to verify updates and release them to the store? Do you do that or do I need to change anything when I make a PR?

**Comment by rowin1** [comment]
Hey @karllhughes , it is bit of a manual process to update the extension in the Chrome Web Store at the moments.  There's probably something out there available to automate the process, but for now I'll get all these changes in and then make a release and upload it.

**Comment by karllhughes** [comment]
I figured. Let me know if there's any other ideas I can help with. I still have a couple wishlist items, but they might be difficult to implement.
