### ISSUE TITLE
Tooltip Error for Chrome

### ISSUE THREAD

**Issue by Frankiscophil** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#20]
> Uncaught TypeError: this.getType is not a function             battledata.js?073b0b83:873 
>     at getTypeIcon (battledata.js?073b0b83:873)
>     at Array.map (<anonymous>)
>     at showPokemonTooltip.js:546
>     at Array.forEach (<anonymous>)
>     at BattleTooltips.showPokemonTooltip (showPokemonTooltip.js:544)
>     at BattleTooltips.showTooltip (battle-tooltips.js?146e10ff:316)
>     at HTMLDivElement.BattleTooltips.showTooltipEvent (battle-tooltips.js?146e10ff:243)
>     at HTMLDivElement.dispatch (jquery-2.1.4.min.js:3)
>     at HTMLDivElement.r.handle (jquery-2.1.4.min.js:3)

This error shows up whenever I hover over a Pokemon icon during battle, both on my and my opponent's side. 

I hope this issue is resolved as soon as your life schedule can make it possible. Have a good day.

**Comment by karllhughes** [comment]
Thanks for the heads up. I'll take a look at this this weekend. Will update you if I figure it out.

**Comment by karllhughes** [comment]
Apparently, something changed in the Pokemon Showdown client which broke our extension. I made a PR, so @rowin1 can review and deploy the fix when he gets time.

I just made the fix for Chrome, but if anyone notices this same issue in Firefox, let me know and we can fix that too. I don't currently use Firefox, so I'm not sure.

**Comment by rowin1** [comment]
Slight delay with the release -- Chrome won't take the new package update because of missing icons or description, both of which the extension has so I'm unsure how to fix.

**Comment by karllhughes** [comment]
This looks fixed now, so I think we can close it, right?

**Comment by rowin1** [comment]
Chrome store is still reviewing the updated package. Version 1.2.2 is borken for whatever reason, even though locally the changes worked. I'll close this issue though.

Update: Version 1.2.3 seems to be working only after I toggle base stats on.
