### ISSUE TITLE
Merging Firefox + Chrome codebases?

### ISSUE THREAD

**Issue by karllhughes** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#23]
Just curious, but is this possible?

Maintaining two nearly identical versions of the codebase isn't ideal. I'm happy to dive into this, but haven't done any Firefox extension work before, so I'll just have to get into that.

**Comment by rowin1** [comment]
I'm happy to consolidate into one codebase but there seems to be differences across the platforms that aren't able to be resolved with the difference in packages. Open to any solutions, though!

**Comment by karllhughes** [comment]
Dove in this weekend and got it working using Webpack. I realize it's a pretty significant restructuring, but it's the only way I know to handle this sort of thing.
