### ISSUE TITLE
Aren't we able to show enemy pokemon stats anymore?

### ISSUE THREAD

**Issue by Hidend** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#5]
I renemger in old version, we were able to see enemy pokemon stats, is it possible to implement that again?
[
![image](https://user-images.githubusercontent.com/20710332/55672717-9470ac80-589e-11e9-983b-294de5a6680b.png)
](url)

**Comment by rowin1** [comment]
It used to show _base_ stats, yes! Is that something that would be helpful for you? I can build it as a toggleable option in the extension.

**Comment by Hidend** [comment]
Yes, it was so helpful. If it's possible that would be amazing!

**Comment by rowin1** [comment]
Thanks for opening this issue.  I've added the ability to toggle on/off base stats with #6 

Simply right click the extension icon on the top right of your browser and click 'Show Base Stats'.  Then, if you're already on a Pokemon Showdown page, just reload the page.
