### ISSUE TITLE
Show move types

### ISSUE THREAD

**Issue by karllhughes** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#9]
Is there any way to show the move's type for opposing pokemon?

Something like this:

<img width="304" alt="show-type" src="https://user-images.githubusercontent.com/1103622/66425528-89294580-e9d5-11e9-9b8a-8fa6d0617892.png">

This would be really helpful because with some moves I forget what the type was. I'm happy to brainstorm on this and make a PR with a solution, just wanted to run it by you and see if you had any ideas before I dug in. Thanks!

**Comment by karllhughes** [comment]
I think move type and damage (#8) would be available by looking up the move in the Pokemon Showdown data: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/moves.js

The other (ideal) way to do it would be if that data were already present in the pokemon object, but I haven't run this extension locally to check yet. That's next on my list.

**Comment by karllhughes** [comment]
After looking at it, I see that the `Dex` object has a `getMove` method, which will allow us to get the power, type, and damage of moves.

I'll make a PR with this new data in the overlay.

**Comment by rowin1** [comment]
@karllhughes This is super cool and I would love to add this in.  Thanks for looking into this and making it happen! 😃 🎆
